### root
GET http://localhost:3000

### user
GET http://localhost:3000/user

### user/hello
GET http://localhost:3000/user/hello

### product
GET http://localhost:3000/product

### product/hello
GET http://localhost:3000/product/hello

### category
GET http://localhost:3000/category/123

### page
GET http://localhost:3000/page/321